# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: Trimble.DBADashVisualizer
PackageVersion: 4.20.2
MinimumOSVersion: 10.0.19041.0
InstallerType: exe
Scope: user
InstallModes:
- silent
- silentWithProgress
InstallerSwitches:
  Silent: --silent
  SilentWithProgress: --silent
UpgradeBehavior: install
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/trimble-oss/dba-dash/releases/download/4.20.2/DBADash_Visualizer_Setup_4.20.2.exe
  InstallerSha256: 4A551D7254D5214AA1D97D25ACE614D782C628914052061EEF1E3DFCF1419CEE
  ProductCode: DBADash_Visualizer
  AppsAndFeaturesEntries:
  - DisplayName: DBA Dash Visualizer
    Publisher: Trimble, Inc.
    ProductCode: DBADash_Visualizer
ManifestType: installer
ManifestVersion: 1.6.0
